# Generated by Django 2.1 on 2018-08-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ownername',
            new_name='authorname',
        ),
    ]
