# Generated by Django 2.1 on 2018-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0004_auto_20180820_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='authorname',
        ),
        migrations.AddField(
            model_name='message',
            name='authorid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
