# Generated by Django 2.1 on 2018-08-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0005_auto_20180820_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='authorid',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='userdash.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userdash.User'),
        ),
    ]
