# Generated by Django 2.1 on 2018-08-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0006_auto_20180820_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('create_d', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentauthor', to='userdash.User')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdash.Message')),
                ('messageowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageowner', to='userdash.User')),
            ],
        ),
    ]
