# Generated by Django 2.1 on 2018-08-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='messageowner',
        ),
    ]
